CREATE PROCEDURE PR_UPD_AD
(
	@NM_ALUNO VARCHAR(100),
	@NR_RA VARCHAR(20),
	@NM_FUNCIONARIO VARCHAR (100)
)

AS
BEGIN
	
	IF ((SELECT NR_RA FROM TB_AD WHERE NR_RA = @NR_RA) = @NR_RA)
	BEGIN
		UPDATE TB_AD
		SET 
			NM_ALUNO = @NM_ALUNO,
			NR_RA = @NR_RA
		WHERE
			NR_RA = @NR_RA
	END
	
	ELSE IF ((SELECT NM_ALUNO FROM TB_AD WHERE NM_ALUNO = @NM_ALUNO) = @NM_ALUNO)
	BEGIN
		UPDATE TB_AD
		SET 
			NM_ALUNO = @NM_ALUNO,
			NR_RA = @NR_RA
		WHERE
			NM_ALUNO = @NM_ALUNO
	END

END

EXEC PR_UPD_AD
	@NR_RA = '100.245.543-10/SP',
	@NM_ALUNO = 'Luciano Romão',
	@NM_FUNCIONARIO = 'Luís Carlos'

SELECT * FROM TB_AD
SELECT NM_ALUNO FROM TB_AD WHERE NM_ALUNO = 'Thaís Quitéria da Rocha Guimarães Rogério'