--CREATE TABLE TB_LOG_INS
--(
--	CD_ID INT IDENTITY NOT NULL,
--	DT_LOG DATETIME NOT NULL,
--	DS_LOG VARCHAR (100) NOT NULL,
--	NM_FUNCIONARIO VARCHAR (100) NOT NULL
--)

USE DB_ESCOLA
GO

CREATE TRIGGER TR_INS_AD
ON TB_AD
FOR INSERT

AS 
BEGIN

	DECLARE
		@NM_ALUNO VARCHAR (100)
	SELECT
		@NM_ALUNO = NM_ALUNO
	FROM
		INSERTED

INSERT INTO TB_LOG_INS
	(DT_LOG,
	DS_LOG,
	NM_FUNCIONARIO)
VALUES
	(GETDATE(),
	@NM_ALUNO + 'foi inserido no Banco de Dados com sucesso!',
	@NM_FUNCIONARIO)
END